test_that("coordinate scoring distinguishes rigid and similarity fits", {
  x <- rbind(c(0, 0, 0), c(1, 0, 0), c(0, 2, 0), c(0, 0, 3))
  r <- diag(c(-1, 1, 1)); z <- sweep(2*x %*% r, 2, c(3, 4, 5), "+")
  fit <- score.coordinates(z, x, alignment = "similarity")
  expect_equal(fit$coords, x, tolerance = 1e-12)
  expect_equal(fit$scale, .5)
  expect_lt(fit$rmse, 1e-12)
  expect_gt(score.coordinates(z, x)$rmse, .1)
  expect_gt(score.coordinates(z, x, "similarity", FALSE)$rmse, .1)
  expect_lt(score.coordinates(sweep(x %*% r, 2, c(3, 4, 5), "+"), x)$rmse, 1e-12)
  unaligned <- score.coordinates(x+1, x, "none")
  expect_equal(unaligned$rmse, sqrt(3))
  expect_equal(unaligned$relative_rmse, unaligned$rmse / sqrt(mean(rowSums(scale(x, scale=FALSE)^2))))
  expect_equal(as.vector(stats::dist(score.coordinates(z, x)$coords)), as.vector(stats::dist(z)))
  expect_equal(score.coordinates(matrix(0, 4, 3), x)$coords,
               matrix(rep(colMeans(x), each=4),4))
  expect_error(score.coordinates(matrix(0,4,3), x, "similarity"), "collapsed")
  expect_true(is.na(score.coordinates(x, matrix(0,4,3))$relative_rmse))
  expect_equal(score.coordinates(x, matrix(0,4,3), "similarity")$scale, 0)
  expect_error(score.coordinates(x[-1, ], x), "dimensions")
  expect_error(score.coordinates(x*NA, x))
  expect_error(score.coordinates(x, x, allow_reflection = NA))
  expect_error(score.coordinates(x, x, "unknown"))
  # Higher-dimensional coordinates and rank-deficient configurations are allowed.
  expect_lt(score.coordinates(cbind(x, x), cbind(x, x))$rmse, 1e-12)
  expect_lt(score.coordinates(matrix(1:4, ncol=1)+7, matrix(1:4,ncol=1))$rmse, 1e-12)
})

test_that("point-to-triangle distances resolve interiors, edges and corners", {
  v <- rbind(c(0,0,0), c(1,0,0), c(0,1,0))
  f <- matrix(1:3,1)
  p <- rbind(c(.2,.3,2), c(.8,.8,0), c(-1,-1,0), c(.5,-1,1), c(0,0,0))
  expect_equal(grip_surface_distances_cpp(p,v,f), c(2,sqrt(.18),sqrt(2),sqrt(2),0), tolerance=1e-12)
  flat <- rbind(c(0,0,0),c(1,0,0),c(2,0,0))
  expect_equal(grip_surface_distances_cpp(matrix(c(1,2,0),1),flat,f),2)
  set.seed(71)
  vertices <- matrix(rnorm(180),ncol=3)
  faces <- matrix(1:60,ncol=3,byrow=TRUE)
  points <- matrix(rnorm(90),ncol=3)
  brute <- vapply(seq_len(nrow(faces)),function(i)
    grip_surface_distances_cpp(points,vertices,faces[i,,drop=FALSE]), numeric(nrow(points)))
  expect_equal(grip_surface_distances_cpp(points,vertices,faces), apply(brute,1,min), tolerance=1e-12)
})

test_that("surface area sampling, distance units and uncertainty are explicit", {
  x <- rbind(c(0,0,0),c(1,0,0),c(0,1,0),c(1,1,0))
  f <- rbind(c(1,2,3),c(2,4,3))
  y <- sweep(x,2,c(0,0,2),"+")
  s <- score.surface(x,f,y,f,sample_size=1000)
  expect_equal(s$rms,2,tolerance=1e-12)
  expect_equal(s$forward_rms,2,tolerance=1e-12)
  expect_equal(s$reverse_mean,2,tolerance=1e-12)
  expect_equal(s$rms_mc_se,0,tolerance=1e-12)
  expect_equal(s$area,1)
  expect_equal(score.surface(x,f,x,f,100)$rms,0,tolerance=1e-12)
  alternative <- rbind(c(1,2,4),c(1,4,3))
  expect_equal(score.surface(x,f,x,alternative,100)$rms,0,tolerance=1e-12)
  expect_equal(score.surface(3*x,f,3*y,f,100)$rms,6,tolerance=1e-12)
  # Closest points on a face interior beat nearest-vertex distances.
  expect_gt(min(sqrt(rowSums((x-matrix(c(.5,.5,0),4,3,byrow=TRUE))^2))),0)
  mesh <- .reference.mesh(x,f,"test")
  set.seed(1); p <- .reference.sample(mesh,20000)
  expect_true(all(p[,1:2]>=0 & p[,1:2]<=1))
  expect_equal(colMeans(p),c(.5,.5,0),tolerance=.015)
  large <- rbind(x, c(4,0,0),c(0,2,0))
  m <- .reference.mesh(large,rbind(c(1,2,3),c(2,5,6)),"test")
  set.seed(2); points <- .reference.sample(m,50000)
  # Mean of an area mixture equals the area-weighted triangle centroid.
  centroids <- t(apply(m$triangles,1,function(i) colMeans(large[i,,drop=FALSE])))
  expect_equal(colMeans(points),colSums(centroids*m$areas)/sum(m$areas),tolerance=.02)
})

test_that("surface scoring restores RNG and rejects invalid surfaces", {
  x <- rbind(c(0,0,0),c(1,0,0),c(0,1,0)); f <- matrix(1:3,1)
  set.seed(9); before <- .Random.seed; kind <- RNGkind()
  a <- score.surface(x,f,x,f,100,2)
  expect_identical(.Random.seed,before); expect_identical(RNGkind(),kind)
  expect_identical(a,score.surface(x,f,x,f,100,2))
  expect_error(score.surface(x,f,x,f,1))
  expect_error(score.surface(x,f,x,f,2.5))
  expect_error(score.surface(x,f,x,f,100,NA))
  expect_error(score.surface(x,f,x,f,100,2147483647))
  expect_error(score.surface(x[,1:2],f,x,f))
  expect_error(score.surface(x,f*0,x,f))
  expect_error(score.surface(x,matrix(c(1,1,2),1),x,f))
  expect_error(score.surface(x,rbind(f,f[,3:1]),x,f),"Duplicate")
  expect_error(score.surface(x*0,f,x,f),"positive total")
  flat <- rbind(x,c(2,0,0))
  expect_warning(s <- score.surface(flat,rbind(f,c(1,2,4)),x,f,100),"zero-area")
  expect_equal(s$zero_area_faces,1)
})
