% !TeX root = RJwrapper.tex
\title{Grip: fast multiscale 2D and 3D graph layout in R}


\author{by Pawel Gajer and Jacques Ravel}

\maketitle

\abstract{%
Grip is an R package for fast multiscale graph layout in 2D and 3D. It brings the GRIP algorithm to R through a C++ core accessed with Rcpp, making it practical to generate layouts for graphs with hundreds to thousands of vertices, including structured synthetic families and larger weighted biological networks. The package provides a topology-first API for unweighted graphs, a weighted sister API for graphs whose edge lengths encode geometry, package-supplied presets for recurring graph families, and a workflow for scoring and comparing candidate layouts reproducibly. This article focuses on the package interface, representative runtime scale, the layout assessment workflow, and two example settings: a weighted geometric graph and a large microbial-network case study.
}

\section{Introduction}\label{introduction}

Many R users need graph layouts that are fast enough to be part of ordinary
exploration rather than one-off figure preparation. That need becomes most
acute once graphs grow beyond toy size, when repeated tuning of single-scale
force-directed methods becomes expensive, and when analysts want 3D embeddings
instead of only 2D drawings. The central package claim of grip is therefore
practical speed: it makes multiscale 2D and 3D graph layout available in R for
graphs large enough that manual trial-and-error is no longer convenient.

The original GRIP algorithm \citep{gajer2002, gajer2004} addresses this problem by
constructing a hierarchy of maximal independent sets, placing vertices from
coarse to fine resolution, and refining locally at each level. The grip package
exposes this multiscale strategy in R through a C++ core accessed with Rcpp
\citep{eddelbuettel2011}. In practice, that hierarchy is what makes it feasible to
produce layouts for graphs with hundreds to thousands of vertices within an R
workflow, including both 2D and 3D embeddings.

This article makes three package-level points. First, grip provides fast
multiscale layout generation through two closely related interfaces: a
topology-first API for unweighted graphs and a weighted sister API for graphs
whose edge lengths encode geometry. Second, the package ships family-specific
presets, trace diagnostics, and graph generators that make larger layout jobs
easier to run and inspect. Third, grip includes a comparison workflow that
evaluates candidate layouts across seeds with shared quality metrics, so that
layout selection is reproducible rather than purely visual.

The package is complementary to existing R tools rather than a replacement for
them. igraph \citep{csardi2006} supplies several strong general-purpose layouts;
ggraph \citep{pedersen2024} provides a plotting grammar for network graphics; and
graphlayouts \citep{schoch2023} offers additional layout algorithms, including
stress-based methods. The contribution of grip is the combination of fast
multiscale layout generation, geometry-aware weighted layouts, and a scoring
workflow that can also be used to assess layouts computed elsewhere.

\section{Package overview}\label{package-overview}

At a high level, grip keeps the original GRIP idea of working from a coarse
representation of the graph back to the full graph. The paper does not attempt
to re-derive the algorithm in detail; instead, it focuses on the package
interfaces that expose this strategy in a form suitable for routine R use. The
practical consequence of that hierarchy is speed: the package can produce 2D
and 3D layouts quickly enough to support comparison workflows rather than only
single final figures.

\subsection{Layout engines and interfaces}\label{layout-engines-and-interfaces}

The main layout functions are summarized in Table \ref{tab:api-summary}. All
return an \(n \times d\) numeric matrix of coordinates, where \(d\) is 2 or 3.

\begin{table}

\caption{\label{tab:api-summary}Core layout interfaces in the grip package.}
\centering
\begin{tabular}[t]{l|l|l}
\hline
Function & Purpose & Graph type\\
\hline
grip.layout() & Combinatorial multiscale layout & Unweighted\\
\hline
grip.layout.trace() & Combinatorial layout with per-level snapshots & Unweighted\\
\hline
grip.layout.weighted() & Weighted multiscale layout & Weighted\\
\hline
grip.layout.trace.weighted() & Weighted layout with per-level snapshots & Weighted\\
\hline
\end{tabular}
\end{table}

The two APIs are intentionally separate. \texttt{grip.layout()} is the default entry
point for unweighted or topology-first graphs. \texttt{grip.layout.weighted()} uses
the same broad parameter vocabulary, but it treats edge lengths as part of the
optimization problem and therefore solves a different task. The traced variants
record intermediate states and diagnostics for inspection or animation.

The package accepts graphs either as two-column integer edge matrices or as
adjacency lists with optional parallel weight lists. A minimal example of both
calling patterns is shown below.

\begin{verbatim}
library(grip)

edges <- edges.mesh(8, 8)
coords.mesh <- grip.layout(edges, n = 64, dim = 2, preset = "mesh", seed = 1)

adj.list <- list(c(2L), c(1L, 3L), c(2L, 4L), c(3L))
weight.list <- list(c(1.0), c(1.0, 2.0), c(2.0, 1.5), c(1.5))
coords.weighted.small <- grip.layout.weighted(
  adj_list = adj.list,
  weight_list = weight.list,
  n = 4,
  dim = 2,
  seed = 12
)
\end{verbatim}

The most important user-facing parameters are layout dimension, initialization
placement, the number of multiscale and final refinement rounds, local
neighborhood size, repulsion strength, and the random seed. The package also
packs disconnected components by default, so disconnected graphs can still be
laid out with a single call.

\subsection{Geodesic and multiscale families}\label{geodesic-and-multiscale-families}

The package also includes geodesic scoring and optimization tools, but they are
not all solving the same problem. Table \ref{tab:family-scope} summarizes the
main exported families and their role in this manuscript.

\begin{table}

\caption{\label{tab:family-scope}Scope of the main layout and geodesic optimization families in grip.}
\centering
\begin{tabular}[t]{l|l|l}
\hline
Family & Exported entry points & Role\\
\hline
grip.layout* & grip.layout*() & Primary user-facing multiscale layout APIs for fast 2D and 3D graph embedding.\\
\hline
geodesic.kk & grip.prepare/score/optimize.geodesic.kk() & Full geodesic-KK scoring and optimization for weighted graph metrics, most useful for evaluation and smaller weighted problems.\\
\hline
landmark.geodesic.kk & grip.prepare/score/optimize.landmark.geodesic.kk() & Sparse landmark geodesic-KK approximation used for post-polish and experimental weighted refinement.\\
\hline
misf.geodesic.mds & grip.prepare/score/optimize.misf.geodesic.mds() & Experimental MISF-based geodesic-MDS pipeline rather than a standalone MISF geodesic-KK family.\\
\hline
\end{tabular}
\end{table}

This distinction matters for the paper. grip already includes pure geodesic-KK
tools, standalone landmark geodesic-KK tools, and MISF-based GMDS tools. It
also integrates LGKK refinement inside the main multiscale solver. However, the
current package does not yet expose a separate standalone \texttt{grip.*misf*.geodesic.kk()}
family, so this package paper keeps the main focus on the \texttt{grip.layout*()}
interfaces and uses the geodesic tools mainly for weighted scoring and
polishing.

\subsection{Presets, tracing, and graph families}\label{presets-tracing-and-graph-families}

The package includes family-specific presets for common graph classes. The
combinatorial interface provides presets for meshes, carpets, trees, and tori.
The weighted interface adds presets for cylinders, spheres, irregular
manifolds, and other families where graph geometry matters. These presets are
starting points, not guarantees of optimality, but they are useful because they
make the package easier to use on recurring graph families.

The trace functions expose the coarse-to-fine solve explicitly. Figure
\ref{fig:trace} shows four trace frames for a small mesh layout.

\begin{figure}

{\centering \includegraphics[width=1\linewidth,alt={Four panels showing a mesh layout evolving from a sparse coarse configuration to a regular grid-like final arrangement.}]{grip-paper-v3_files/figure-latex/trace-1} 

}

\caption{Multiscale trace of a 6x6 mesh. The four panels show the coarsest initialization, an early intermediate state, a late intermediate state, and the final layout.}\label{fig:trace}
\end{figure}

The package also ships graph generators for regular grids, trees, recursive
families such as Sierpinski carpets, and weighted geometric families generated
from surfaces. These are helpful for examples, regression tests, and
family-specific benchmarking.

\subsection{Representative runtime scale}\label{representative-runtime-scale}

The main software claim of grip is practical runtime scale rather than a claim
to dominate every other layout method on every graph. Table
\ref{tab:runtime-scale} therefore summarizes three representative layouts that
cover both 2D and 3D settings. The torus row is evaluated directly in the paper
build, while the larger carpet and HMP rows use bundled package artifacts so
that the manuscript remains quick to render.

\begin{table}

\caption{\label{tab:runtime-scale}Representative 2D and 3D runtime scale for grip. Abbrev.: nV = number of vertices; nE = number of edges; Sec = elapsed seconds; Stress = sampled stress.}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
Graph & Dim & nV & nE & context & elapsed.sec & Stress\\
\hline
20x20 torus & 3 & 400 & 800 & Single 3D preset solve & 0.349 & 35.709\\
\hline
Carpet level 4 & 2 & 4096 & 6424 & Single 2D preset solve & 2.184 & 175.422\\
\hline
HMP/U01 coarse & 3 & 1828 & 4656 & Bundled weighted 3D default candidate & 12.247 & 93.923\\
\hline
\end{tabular}
\end{table}

These rows are not intended as a formal benchmark against all alternatives.
They show the practical regime the package is designed for: graphs with
hundreds to thousands of vertices, including 3D embeddings and a weighted
real-data example, can be laid out in seconds rather than forcing users into a
slow manual tuning loop.

\section{Layout assessment workflow}\label{layout-assessment-workflow}

The strongest package-level feature of grip is not that it always produces the
best layout on every graph. Rather, it gives users a reproducible way to score
candidate layouts, compare them across seeds, and inspect the trade-offs
between graph families and layout objectives.

\subsection{Quality metrics}\label{quality-metrics}

Table \ref{tab:metrics-table} summarizes the metrics returned by
\texttt{grip.score.layout()}. The package uses them directly for single-layout scoring
and for aggregate comparisons across seeds in \texttt{grip.compare.layouts()}.

\begin{table}

\caption{\label{tab:metrics-table}Quality metrics used by grip.score.layout().}
\centering
\begin{tabular}[t]{l|l|l}
\hline
Metric & Meaning & Better\\
\hline
Sampled stress & Agreement between layout distances and graph distances & Lower\\
\hline
Edge-length CV & Uniformity of edge lengths & Lower\\
\hline
Sampled non-edge separation & Breathing room between non-neighbors & Higher\\
\hline
Edge crossings & Readability in 2D & Lower\\
\hline
Cluster separation & Separation of known external groups & Higher\\
\hline
Procrustes stability & Seed-to-seed reproducibility & Lower\\
\hline
\end{tabular}
\end{table}

\texttt{grip.compare.layouts()} runs multiple candidates across seeds, computes these
metrics for each run, and returns both run-level and summary-level results. The
summary includes mean quality metrics, a rank-based composite score, and a
Procrustes stability estimate when multiple seeds are used.

\subsection{Evidence for family-specific presets}\label{evidence-for-family-specific-presets}

To make the preset claims concrete, Table \ref{tab:preset-benchmark} compares
the default layout settings with package-supplied presets on two structured
families, each run across three seeds. The results are generated directly in
the paper build.

\begin{table}

\caption{\label{tab:preset-benchmark}Preset benchmark on two structured graph families, each averaged over three seeds. Abbrev.: Runs = number of seeds; Sec = mean elapsed seconds; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; PStab = Procrustes stability.}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r|r}
\hline
Graph & Cand & Runs & Sec & Stress & EdgeCV & NESR & PStab\\
\hline
12x12 mesh & default & 3 & 0.612 & 41.956 & 0.122 & 0.134 & 0.490\\
\hline
12x12 mesh & mesh & 3 & 0.727 & 19.785 & 0.050 & 1.214 & 0.005\\
\hline
Carpet level 3 & default & 3 & 0.217 & 133.750 & 0.208 & 0.048 & 0.562\\
\hline
Carpet level 3 & carpet & 3 & 0.606 & 54.504 & 0.120 & 1.090 & 0.014\\
\hline
\end{tabular}
\end{table}

These results show why the presets matter. On both graph families, the
package-supplied preset reduces sampled stress, improves edge-length
uniformity, increases non-edge separation, and is substantially more stable
across seeds. The runtime cost is small relative to the improvement in layout
quality on these families.

\section{Worked examples}\label{worked-examples}

\subsection{Family-specific improvement on a recursive graph}\label{family-specific-improvement-on-a-recursive-graph}

Figure \ref{fig:carpet-figure} visualizes the Sierpinski-carpet benchmark from
the previous section. The figure is paired with the benchmark table so that the
claim is visual and quantitative rather than purely visual.

\begin{figure}

{\centering \includegraphics[width=1\linewidth,alt={Two panels showing a Sierpinski carpet graph. The default layout is more distorted, while the preset layout better preserves the recursive holes.}]{grip-paper-v3_files/figure-latex/carpet-figure-1} 

}

\caption{Level-3 Sierpinski carpet laid out with the default settings (left) and the carpet preset (right). The preset yields the lower-stress and more stable solution reported in Table \\ref{tab:preset-benchmark}.}\label{fig:carpet-figure}
\end{figure}

\subsection{Weighted graph with geometric edge lengths}\label{weighted-graph-with-geometric-edge-lengths}

The weighted interface is easiest to motivate on a graph whose topology is
simple but whose geometry is not. The example below uses a \(5 \times 5\) mesh
whose edge lengths are induced by a curved saddle surface. The graph topology
is unchanged, but the intended metric is no longer the flat grid metric.

The comparison includes three candidates: the combinatorial layout, the
weighted layout, and the weighted layout followed by a small amount of LGKK
polish. The scoring uses \texttt{grip.score.geodesic.kk()}, which evaluates the
layout against the weighted graph metric.

\begin{table}

\caption{\label{tab:weighted-summary}Weighted saddle-surface example scored with geodesic-KK criteria. Abbrev.: GKK Rel = weighted relative RMSE; GKK RMSE = weighted RMSE; Path Rel = mean relative path error.}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Meth & GKK Rel & GKK RMSE & Path Rel\\
\hline
Combinatorial GRIP & 0.194 & 7.151 & 0.098\\
\hline
Weighted GRIP & 0.103 & 3.777 & 0.054\\
\hline
Weighted GRIP + LGKK polish & 0.003 & 0.106 & 0.001\\
\hline
\end{tabular}
\end{table}

On this example, the weighted solve lowers the weighted relative RMSE from
0.194 to
0.103, and a short LGKK
polish reduces it further to
0.003. This is the package
argument for the weighted API: it is not only another parameter setting, but a
different interface for graphs where edge lengths are part of the target.

\begin{figure}

{\centering \includegraphics[width=1\linewidth,alt={A four-panel comparison of a saddle-surface mesh showing the target geometry, the combinatorial layout, the weighted layout, and the weighted layout with LGKK polish.}]{grip-paper-v3_files/figure-latex/weighted-figure-1} 

}

\caption{Weighted mesh example. Top left: target saddle geometry. Top right: combinatorial GRIP. Bottom left: weighted GRIP. Bottom right: weighted GRIP followed by LGKK polish.}\label{fig:weighted-figure}
\end{figure}

\subsection{Large real-data example: HMP microbial network}\label{large-real-data-example-hmp-microbial-network}

The package bundles a coarsened graph derived from Human Microbiome Project
data \citep{hmp2012}. The original giant connected component had 6,474 vertices; the
bundled coarsened graph has 1,828 vertices and 4,656 edges, which is large
enough that ad hoc manual layout selection becomes impractical. This example is
included not only for biological realism but also because it shows that a
weighted 3D workflow at this graph size is still practical inside R.

\begin{verbatim}
#> Vertices: 1828
#> Edges: 4656
#> CST levels: I, II, III, IV-A, IV-B, IV-C, V
\end{verbatim}

The full HMP workflow uses repeated scoring and candidate comparison, so the
package ships precomputed artifacts for the vignette and the paper. Even in
that broader workflow, the bundled default weighted candidate runs in about
12.2
seconds. Table \ref{tab:hmp-summary} reports three candidates: the default
preset, the tree preset, and the strongest local-search candidate by
cluster-separation score among the bundled precomputed results.

\begin{table}

\caption{\label{tab:hmp-summary}Precomputed HMP candidate summary for the bundled 1,828-vertex graph. Abbrev.: Sec = elapsed seconds; Stress = sampled stress; NESR = sampled non-edge separation ratio; ClSep = cluster separation; Comp = composite score.}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
Cand & Sec & Stress & NESR & ClSep & Comp\\
\hline
default & 12.247 & 93.923 & 0.454 & 1.693 & 0.062\\
\hline
tree & 12.434 & 96.322 & 0.290 & 3.400 & 0.594\\
\hline
local search & 12.732 & 96.333 & 0.205 & 3.407 & 0.333\\
\hline
\end{tabular}
\end{table}

The table shows a real trade-off. The default candidate is the fastest of the
three and has the lowest sampled stress, while the tree and local-search
candidates produce substantially larger cluster-separation scores. That is
exactly the kind of choice the comparison workflow is meant to surface: speed
makes it practical to inspect several plausible 3D layouts, but the package
still leaves the final selection explicit and evidence-based.

\begin{figure}

{\centering \includegraphics[width=1\linewidth,alt={Three orthographic 3D network layouts of the HMP graph colored by community state type, comparing default, tree, and local-search candidates.}]{grip-paper-v3_files/figure-latex/hmp-figure-1} 

}

\caption{Precomputed 3D layouts for the HMP microbial network, colored by community state type. Left: default candidate. Middle: tree preset. Right: best precomputed local-search candidate by cluster-separation score.}\label{fig:hmp-figure}
\end{figure}

\section{Comparison with other R tools}\label{comparison-with-other-r-tools}

For package evaluation, the most useful comparison is not a checklist of
features but an evidence-based benchmark. Table \ref{tab:karate-benchmark}
therefore uses bundled precomputed results on the Zachary karate club graph
\citep{zachary1977}, scored with the same layout-quality metrics for all methods.

\begin{table}

\caption{\label{tab:karate-benchmark}Small-graph comparison on the Zachary karate club network using a shared scoring function. Abbrev.: Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; ClSep = cluster separation; Cross = edge crossings.}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
Meth & Stress & EdgeCV & NESR & ClSep & Cross\\
\hline
FR (igraph) & 1.220 & 0.358 & 0.367 & 2.757 & 68\\
\hline
KK (igraph) & 0.614 & 0.281 & 0.302 & 2.253 & 73\\
\hline
DrL (igraph) & 0.605 & 0.468 & 0.237 & 1.658 & 120\\
\hline
Stress (graphlayouts) & 0.520 & 0.261 & 0.275 & 2.224 & 78\\
\hline
grip default & 13.825 & 0.279 & 0.083 & 0.266 & 301\\
\hline
grip tuned & 18.123 & 0.285 & 0.118 & 0.561 & 246\\
\hline
\end{tabular}
\end{table}

This comparison is intentionally modest in tone. On a very small 2D social
graph, single-scale methods from igraph and graphlayouts perform very well, and
grip does not dominate them. That is an informative result. It supports the
claim that grip is most useful as a fast multiscale and evaluation-oriented
package,
especially for structured graph families, weighted geometric graphs, and
workflow-driven layout selection. It also illustrates why the scoring
functions are valuable on their own: they can be used to assess layouts
computed outside the package.

\section{Reproducibility}\label{reproducibility}

This article is written in R Markdown using the rjtools output format currently
recommended by the journal. The tables and the small-graph figures are produced
from evaluated code in the manuscript. The larger HMP case study and the
external-package comparison both use bundled precomputed \texttt{.rds} artifacts so
that the paper can be rendered quickly during review while still pointing to
the scripts and vignettes that generate those artifacts.

In the package source tree, the external comparison artifacts are created by
\texttt{inst/scripts/precompute-vs-alternatives.R}, and the HMP workflow is described
in the real-data vignette and the HMP case-study article. This split keeps the
paper build practical without hiding how the heavier results were produced.

\section{Discussion}\label{discussion}

The manuscript-level conclusion is deliberately narrower than a methods paper.
grip is useful because it brings fast multiscale 2D and 3D layout generation
and a reproducible assessment workflow into R, not because it wins every
benchmark. The package is strongest in three settings:

\begin{itemize}
\tightlist
\item
  graphs large enough that single-scale manual tuning becomes slow, especially
  when 3D embeddings are useful;
\item
  weighted graphs whose edge lengths encode geometry and should therefore be
  solved with the weighted sister API rather than treated as ordinary metadata;
\item
  analysis workflows where several plausible layouts must be compared
  reproducibly rather than selected by eye.
\end{itemize}

There are also clear limits. The preset library is finite, so some real graphs
will still require manual tuning. The quality metrics are proxies for readable
drawings rather than guarantees of optimality. Exact edge-crossing counts are
expensive on dense 2D graphs, and the current implementation does not use GPU
acceleration for very large problems. These are reasonable boundaries for a
package paper and help clarify where the package fits in the current R
ecosystem.

The package source code, vignettes, and issue tracker are available at
\url{https://github.com/pgajer/grip}.

\section{Acknowledgments}\label{acknowledgments}

The GRIP algorithm was originally developed in collaboration with Stephen G.
Kobourov and Michael T. Goodrich. The HMP microbial network data were derived
from publicly available Human Microbiome Project resources. Research reported
in this publication was supported by grant number INV-048956 from the Gates
Foundation.

\bibliography{grip-paper-v3.bib}

\address{%
Pawel Gajer\\
Center for Advanced Microbiome Research and Innovation (CAMRI), Institute for Genome Sciences, Department of Microbiology and Immunology, University of Maryland School of Medicine\\%
Baltimore, Maryland, USA\\
%
%
%
\href{mailto:pgajer@gmail.com}{\nolinkurl{pgajer@gmail.com}}%
}

\address{%
Jacques Ravel\\
Center for Advanced Microbiome Research and Innovation (CAMRI), Institute for Genome Sciences, Department of Microbiology and Immunology, University of Maryland School of Medicine\\%
Baltimore, Maryland, USA\\
%
%
%
%
}
