# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit grip-paper-v3.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  fig.width = 7,
  fig.height = 4.5,
  fig.align = "center",
  out.width = "100%",
  message = FALSE,
  warning = FALSE
)

paper.table.colnames <- c(
  graph = "Graph",
  candidate = "Cand",
  method = "Meth",
  dim = "Dim",
  `n.vertices` = "nV",
  `n.edges` = "nE",
  `n.runs` = "Runs",
  `elapsed.sec.mean` = "Sec",
  `score.composite` = "Comp",
  `sampled.stress` = "Stress",
  `sampled.stress.mean` = "Stress",
  `edge.length.cv` = "EdgeCV",
  `edge.length.cv.mean` = "EdgeCV",
  `sampled.nonedge.sep.ratio` = "NESR",
  `sampled.nonedge.sep.ratio.mean` = "NESR",
  `cluster.separation` = "ClSep",
  `cluster.separation.mean` = "ClSep",
  `stability.procrustes.mean` = "PStab",
  `edge.crossings` = "Cross",
  `gkk.weighted.rel.rmse` = "GKK Rel",
  `gkk.weighted.rmse` = "GKK RMSE",
  `gkk.mean.rel.path.error` = "Path Rel"
)

paper_table_caption <- function(title, abbreviations) {
  paste0(title, " Abbrev.: ", abbreviations)
}

paper_kable <- function(x, caption, digits = 3) {
  col.names <- unname(ifelse(
    names(x) %in% names(paper.table.colnames),
    paper.table.colnames[names(x)],
    names(x)
  ))
  align <- c("l", rep("r", max(0, ncol(x) - 1L)))
  knitr::kable(
    x,
    digits = digits,
    col.names = col.names,
    row.names = FALSE,
    align = align,
    caption = caption
  )
}

find.extdata.file <- function(...) {
  rel.path <- file.path(...)
  candidates <- c(
    system.file("extdata", rel.path, package = "grip"),
    file.path("..", "..", "..", "..", "inst", "extdata", rel.path),
    file.path("..", "..", "..", "inst", "extdata", rel.path),
    file.path("inst", "extdata", rel.path)
  )
  path <- candidates[file.exists(candidates)][1L]
  if (!length(path) || is.na(path) || !nzchar(path)) {
    stop("could not locate ", rel.path)
  }
  path
}

read.extdata.csv <- function(file.name) {
  utils::read.csv(find.extdata.file(file.name), stringsAsFactors = FALSE)
}

read.extdata.rds <- function(...) {
  readRDS(find.extdata.file(...))
}

plot_layout_panel <- function(coords,
                              edges,
                              main,
                              projection = NULL,
                              vertex.col = "black",
                              edge.col = "gray82",
                              cex = 0.5) {
  grip.plot(
    coords, edges,
    projection = projection,
    vertex.col = vertex.col,
    edge.col = edge.col,
    pch = 16,
    cex = cex,
    main = main
  )
}

edge.matrix.from.adj <- function(adj.list) {
  edges <- list()
  idx <- 0L
  for (u in seq_along(adj.list)) {
    nbrs <- adj.list[[u]][adj.list[[u]] > u]
    for (v in nbrs) {
      idx <- idx + 1L
      edges[[idx]] <- c(u, v)
    }
  }
  do.call(rbind, edges)
}


## ----api-summary, echo=FALSE--------------------------------------------------
api.summary <- data.frame(
  Function = c(
    "grip.layout()",
    "grip.layout.trace()",
    "grip.layout.weighted()",
    "grip.layout.trace.weighted()"
  ),
  Purpose = c(
    "Combinatorial multiscale layout",
    "Combinatorial layout with per-level snapshots",
    "Weighted multiscale layout",
    "Weighted layout with per-level snapshots"
  ),
  `Graph type` = c("Unweighted", "Unweighted", "Weighted", "Weighted"),
  check.names = FALSE
)

knitr::kable(
  api.summary,
  row.names = FALSE,
  align = c("l", "l", "l"),
  caption = "Core layout interfaces in the grip package."
)


## ----api-examples, echo=TRUE--------------------------------------------------
library(grip)

edges <- edges.mesh(8, 8)
coords.mesh <- grip.layout(edges, n = 64, dim = 2, preset = "mesh", seed = 1)

adj.list <- list(c(2L), c(1L, 3L), c(2L, 4L), c(3L))
weight.list <- list(c(1.0), c(1.0, 2.0), c(2.0, 1.5), c(1.5))
coords.weighted.small <- grip.layout.weighted(
  adj_list = adj.list,
  weight_list = weight.list,
  n = 4,
  dim = 2,
  seed = 12
)


## ----trace, fig.cap="Multiscale trace of a 6x6 mesh. The four panels show the coarsest initialization, an early intermediate state, a late intermediate state, and the final layout.", fig.alt="Four panels showing a mesh layout evolving from a sparse coarse configuration to a regular grid-like final arrangement.", fig.width=10, fig.height=2.8----
trace.edges <- edges.mesh(6, 6)
trace.solve <- grip.layout.trace(
  trace.edges, n = 36, dim = 2,
  preset = "mesh", seed = 31,
  trace = "level"
)

frame.idx <- unique(c(
  1L,
  max(2L, floor(length(trace.solve$frames) / 3)),
  max(3L, floor(2 * length(trace.solve$frames) / 3)),
  length(trace.solve$frames)
))

labels <- c("Coarsest start", "Early refinement", "Late refinement", "Final layout")
op <- par(mfrow = c(1, 4), mar = c(1, 1, 2.5, 1))
for (i in seq_along(frame.idx)) {
  coords <- trace.solve$frames[[frame.idx[i]]]
  active <- complete.cases(coords[, 1:2])
  xy <- coords[active, 1:2, drop = FALSE]
  active.edges <- trace.edges[active[trace.edges[, 1]] & active[trace.edges[, 2]], , drop = FALSE]

  xlim <- range(xy[, 1])
  ylim <- range(xy[, 2])
  xpad <- max(0.08 * diff(xlim), 0.2)
  ypad <- max(0.08 * diff(ylim), 0.2)

  plot(xy[, 1], xy[, 2], type = "n", asp = 1, axes = FALSE,
       xlab = "", ylab = "",
       xlim = xlim + c(-xpad, xpad),
       ylim = ylim + c(-ypad, ypad),
       main = labels[i])
  if (nrow(active.edges) > 0) {
    segments(
      coords[active.edges[, 1], 1], coords[active.edges[, 1], 2],
      coords[active.edges[, 2], 1], coords[active.edges[, 2], 2],
      col = "gray82"
    )
  }
  points(xy[, 1], xy[, 2], pch = 16, cex = 0.6)
}
par(op)


## ----metrics-table, echo=FALSE------------------------------------------------
metrics.table <- data.frame(
  Metric = c(
    "Sampled stress",
    "Edge-length CV",
    "Sampled non-edge separation",
    "Edge crossings",
    "Cluster separation",
    "Procrustes stability"
  ),
  Meaning = c(
    "Agreement between layout distances and graph distances",
    "Uniformity of edge lengths",
    "Breathing room between non-neighbors",
    "Readability in 2D",
    "Separation of known external groups",
    "Seed-to-seed reproducibility"
  ),
  Better = c("Lower", "Lower", "Higher", "Lower", "Higher", "Lower"),
  check.names = FALSE
)

knitr::kable(
  metrics.table,
  row.names = FALSE,
  align = c("l", "l", "l"),
  caption = "Quality metrics used by grip.score.layout()."
)


## ----preset-benchmark---------------------------------------------------------
mesh.edges <- edges.mesh(12, 12)
mesh.compare <- grip.compare.layouts(
  edges = mesh.edges,
  n = 144,
  dim = 2,
  candidates = c("default", "mesh"),
  seeds = 1:3,
  edge.crossings = "always"
)

carpet.edges <- edges.sierpinski.carpet(3)
carpet.n <- max(carpet.edges)
carpet.compare <- grip.compare.layouts(
  edges = carpet.edges,
  n = carpet.n,
  dim = 2,
  candidates = c("default", "carpet"),
  seeds = 1:3,
  edge.crossings = "never"
)

preset.benchmark <- rbind(
  transform(
    mesh.compare$summary[, c(
      "candidate", "n.runs", "elapsed.sec.mean", "sampled.stress.mean",
      "edge.length.cv.mean", "sampled.nonedge.sep.ratio.mean",
      "stability.procrustes.mean"
    )],
    graph = "12x12 mesh"
  ),
  transform(
    carpet.compare$summary[, c(
      "candidate", "n.runs", "elapsed.sec.mean", "sampled.stress.mean",
      "edge.length.cv.mean", "sampled.nonedge.sep.ratio.mean",
      "stability.procrustes.mean"
    )],
    graph = "Carpet level 3"
  )
)

preset.benchmark <- preset.benchmark[, c(
  "graph", "candidate", "n.runs", "elapsed.sec.mean",
  "sampled.stress.mean", "edge.length.cv.mean",
  "sampled.nonedge.sep.ratio.mean", "stability.procrustes.mean"
)]
preset.benchmark$candidate <- factor(
  preset.benchmark$candidate,
  levels = c("default", "mesh", "carpet")
)
preset.benchmark <- preset.benchmark[order(preset.benchmark$graph, preset.benchmark$candidate), ]

paper_kable(
  preset.benchmark,
  caption = paper_table_caption(
    "Preset benchmark on two structured graph families, each averaged over three seeds.",
    "Runs = number of seeds; Sec = mean elapsed seconds; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; PStab = Procrustes stability."
  ),
  digits = 3
)


## ----carpet-figure, fig.cap="Level-3 Sierpinski carpet laid out with the default settings (left) and the carpet preset (right). The preset yields the lower-stress and more stable solution reported in Table \\@ref(tab:preset-benchmark).", fig.alt="Two panels showing a Sierpinski carpet graph. The default layout is more distorted, while the preset layout better preserves the recursive holes.", fig.width=10, fig.height=4.5----
carpet.default.coords <- grip.layout(carpet.edges, n = carpet.n, dim = 2, seed = 12)
carpet.preset.coords <- grip.layout(carpet.edges, n = carpet.n, dim = 2, preset = "carpet", seed = 12)

op <- par(mfrow = c(1, 2), mar = c(1, 1, 3, 1))
plot_layout_panel(carpet.default.coords, carpet.edges, "Default", cex = 0.3)
plot_layout_panel(carpet.preset.coords, carpet.edges, "Carpet preset", cex = 0.3)
par(op)


## ----weighted-summary---------------------------------------------------------
weighted.mesh <- mesh.surface.graph(5, 5, surface = "saddle", amplitude = 0.8)

coords.combinatorial <- grip.layout(
  weighted.mesh$edges,
  n = weighted.mesh$n,
  dim = 3,
  preset = "mesh",
  seed = 1
)

coords.weighted <- grip.layout.weighted(
  weighted.mesh$edges,
  n = weighted.mesh$n,
  edge_weights = weighted.mesh$edge_weights,
  dim = 3,
  preset = "mesh",
  seed = 1
)

coords.weighted.lgkk <- grip.layout.weighted(
  weighted.mesh$edges,
  n = weighted.mesh$n,
  edge_weights = weighted.mesh$edge_weights,
  dim = 3,
  preset = "mesh",
  lgkk_polish_rounds = 6L,
  seed = 1
)

gkk.prepared <- grip.prepare.geodesic.kk(
  weighted.mesh$edges,
  n = weighted.mesh$n,
  edge_weights = weighted.mesh$edge_weights
)

weighted.summary <- do.call(
  rbind,
  list(
    cbind(
      method = "Combinatorial GRIP",
      grip.score.geodesic.kk(
        coords.combinatorial,
        prepared = gkk.prepared
      )[, c(
        "gkk.weighted.rel.rmse",
        "gkk.weighted.rmse",
        "gkk.mean.rel.path.error"
      )]
    ),
    cbind(
      method = "Weighted GRIP",
      grip.score.geodesic.kk(
        coords.weighted,
        prepared = gkk.prepared
      )[, c(
        "gkk.weighted.rel.rmse",
        "gkk.weighted.rmse",
        "gkk.mean.rel.path.error"
      )]
    ),
    cbind(
      method = "Weighted GRIP + LGKK polish",
      grip.score.geodesic.kk(
        coords.weighted.lgkk,
        prepared = gkk.prepared
      )[, c(
        "gkk.weighted.rel.rmse",
        "gkk.weighted.rmse",
        "gkk.mean.rel.path.error"
      )]
    )
  )
)

paper_kable(
  weighted.summary,
  caption = paper_table_caption(
    "Weighted saddle-surface example scored with geodesic-KK criteria.",
    "GKK Rel = weighted relative RMSE; GKK RMSE = weighted RMSE; Path Rel = mean relative path error."
  ),
  digits = 3
)


## ----weighted-figure, fig.cap="Weighted mesh example. Top left: target saddle geometry. Top right: combinatorial GRIP. Bottom left: weighted GRIP. Bottom right: weighted GRIP followed by LGKK polish.", fig.alt="A four-panel comparison of a saddle-surface mesh showing the target geometry, the combinatorial layout, the weighted layout, and the weighted layout with LGKK polish.", fig.width=11.2, fig.height=8----
op <- par(mfrow = c(2, 2), mar = c(1, 1, 3, 1))
plot_layout_panel(
  weighted.mesh$coords_surface,
  weighted.mesh$edges,
  "Target geometry",
  projection = "ortho",
  vertex.col = "#666666"
)
plot_layout_panel(
  coords.combinatorial,
  weighted.mesh$edges,
  "Combinatorial GRIP",
  projection = "ortho"
)
plot_layout_panel(
  coords.weighted,
  weighted.mesh$edges,
  "Weighted GRIP",
  projection = "ortho",
  vertex.col = "#1F3B73"
)
plot_layout_panel(
  coords.weighted.lgkk,
  weighted.mesh$edges,
  "Weighted GRIP + LGKK",
  projection = "ortho",
  vertex.col = "#7A2E2E"
)
par(op)


## ----hmp-data-----------------------------------------------------------------
data(hmp.u01.gc.coarse)

cat("Vertices:", length(hmp.u01.gc.coarse$adj_list), "\n")
cat("Edges:", nrow(edge.matrix.from.adj(hmp.u01.gc.coarse$adj_list)), "\n")
cat(
  "CST levels:",
  paste(sort(unique(hmp.u01.gc.coarse$vertex_data$cst)), collapse = ", "),
  "\n"
)


## ----hmp-summary--------------------------------------------------------------
hmp.results <- read.extdata.rds("hmp_u01_gc_coarse", "vignette_results.rds")

hmp.local.best.idx <- which.max(hmp.results$local_search_summary$cluster.separation.mean)
hmp.local.best <- hmp.results$local_search_summary[hmp.local.best.idx, , drop = FALSE]
hmp.display <- rbind(
  transform(
    hmp.results$preset_summary[hmp.results$preset_summary$candidate == "default", , drop = FALSE],
    candidate = "default"
  ),
  transform(
    hmp.results$preset_summary[hmp.results$preset_summary$candidate == "tree", , drop = FALSE],
    candidate = "tree"
  ),
  transform(
    hmp.local.best,
    candidate = "local search"
  )
)

hmp.display <- hmp.display[, c(
  "candidate", "elapsed.sec.mean", "sampled.stress.mean",
  "sampled.nonedge.sep.ratio.mean", "cluster.separation.mean",
  "score.composite"
)]

paper_kable(
  hmp.display,
  caption = paper_table_caption(
    "Precomputed HMP candidate summary for the bundled 1,828-vertex graph.",
    "Sec = elapsed seconds; Stress = sampled stress; NESR = sampled non-edge separation ratio; ClSep = cluster separation; Comp = composite score."
  ),
  digits = 3
)


## ----hmp-figure, fig.cap="Precomputed 3D layouts for the HMP microbial network, colored by community state type. Left: default candidate. Middle: tree preset. Right: best precomputed local-search candidate by cluster-separation score.", fig.alt="Three orthographic 3D network layouts of the HMP graph colored by community state type, comparing default, tree, and local-search candidates.", fig.width=11, fig.height=4----
hmp.edges <- edge.matrix.from.adj(hmp.u01.gc.coarse$adj_list)
hmp.cst <- hmp.u01.gc.coarse$vertex_data$cst
cst.levels <- sort(unique(hmp.cst))
cst.cols <- setNames(grDevices::hcl.colors(length(cst.levels), "Dark 3"), cst.levels)
hmp.vertex.cols <- cst.cols[hmp.cst]
hmp.local.name <- as.character(hmp.results$local_search_summary$candidate[hmp.local.best.idx])

op <- par(mfrow = c(1, 3), mar = c(1, 1, 3, 1))
plot_layout_panel(
  hmp.results$layouts$preset$default,
  hmp.edges,
  "Default",
  projection = "ortho",
  vertex.col = hmp.vertex.cols,
  cex = 0.45
)
plot_layout_panel(
  hmp.results$layouts$preset$tree,
  hmp.edges,
  "Tree preset",
  projection = "ortho",
  vertex.col = hmp.vertex.cols,
  cex = 0.45
)
plot_layout_panel(
  hmp.results$layouts$local[[hmp.local.name]],
  hmp.edges,
  "Local search",
  projection = "ortho",
  vertex.col = hmp.vertex.cols,
  cex = 0.45
)
par(op)


## ----karate-benchmark---------------------------------------------------------
benchmark.results <- read.extdata.rds("vs_alternatives", "benchmark_results.rds")

karate.display <- benchmark.results$karate$scores[, c(
  "method",
  "sampled.stress",
  "edge.length.cv",
  "sampled.nonedge.sep.ratio",
  "cluster.separation",
  "edge.crossings"
)]

paper_kable(
  karate.display,
  caption = paper_table_caption(
    "Small-graph comparison on the Zachary karate club network using a shared scoring function.",
    "Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; ClSep = cluster separation; Cross = edge crossings."
  ),
  digits = 3
)

