# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit grip-paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 4.5,
  fig.align = "center",
  out.width = "100%"
)

paper.table.colnames <- c(
  candidate = "Cand",
  method = "Meth",
  `n.vertices` = "nV",
  `n.edges` = "nE",
  dim = "Dim",
  `score.composite` = "Comp",
  `sampled.stress` = "Stress",
  `sampled.stress.mean` = "Stress",
  `edge.length.cv` = "EdgeCV",
  `edge.length.cv.mean` = "EdgeCV",
  `median.edge.length` = "MedEL",
  `sampled.nonedge.sep.ratio` = "NESR",
  `sampled.nonedge.sep.ratio.mean` = "NESR",
  `stability.procrustes.mean` = "PStab",
  `cluster.separation` = "ClSep",
  `cluster.separation.mean` = "ClSep",
  `edge.crossings` = "Cross"
)

paper_table_caption <- function(title, abbreviations) {
  paste0(title, " Abbrev.: ", abbreviations)
}

paper_kable <- function(x, caption, digits = 3) {
  col.names <- unname(ifelse(
    names(x) %in% names(paper.table.colnames),
    paper.table.colnames[names(x)],
    names(x)
  ))
  align <- c("l", rep("r", max(0, ncol(x) - 1L)))
  knitr::kable(
    x,
    digits = digits,
    col.names = col.names,
    row.names = FALSE,
    align = align,
    caption = caption
  )
}

compact_search_candidate <- function(x) {
  out <- sub("^karate\\.local\\.", "", x)
  out <- sub(
    "^final_rounds\\.([0-9]+)\\.num_nbrs\\.([0-9]+)\\.repulsion_factor\\.([0-9.]+)$",
    "fr\\1-nn\\2-rf\\3",
    out
  )
  gsub("\\.", "p", out)
}


## ----trace, fig.cap="Multiscale trace of a 6x6 mesh layout using the mesh preset. From left to right: coarsest initialization with a handful of representative vertices, early refinement introducing additional vertices, late refinement improving spacing, and the final converged layout.", fig.width=10, fig.height=2.8----
library(grip)

edges <- edges.mesh(6, 6)
tr <- grip.layout.trace(
  edges, n = 36, dim = 2,
  preset = "mesh", seed = 31,
  trace = "level"
)

frame.idx <- unique(c(
  1L,
  max(2L, floor(length(tr$frames) / 3)),
  max(3L, floor(2 * length(tr$frames) / 3)),
  length(tr$frames)
))

op <- par(mfrow = c(1, 4), mar = c(1, 1, 2.5, 1))
labels <- c("Coarsest start", "Early refinement",
            "Late refinement", "Final layout")
for (i in seq_along(frame.idx)) {
  coords <- tr$frames[[frame.idx[i]]]
  active <- complete.cases(coords[, 1:2])
  xy <- coords[active, 1:2, drop = FALSE]
  active.edges <- edges[active[edges[, 1]] & active[edges[, 2]], , drop = FALSE]

  xlim <- range(xy[, 1]); ylim <- range(xy[, 2])
  xpad <- max(0.08 * diff(xlim), 0.2)
  ypad <- max(0.08 * diff(ylim), 0.2)

  plot(xy[, 1], xy[, 2], type = "n", asp = 1, axes = FALSE,
       xlab = "", ylab = "",
       xlim = xlim + c(-xpad, xpad),
       ylim = ylim + c(-ypad, ypad),
       main = labels[i])
  if (nrow(active.edges) > 0)
    segments(coords[active.edges[, 1], 1], coords[active.edges[, 1], 2],
             coords[active.edges[, 2], 1], coords[active.edges[, 2], 2],
             col = "gray80")
  points(xy[, 1], xy[, 2], pch = 16, cex = 0.6)
}
par(op)


## -----------------------------------------------------------------------------
# Edge-list input: 8x8 mesh in 2D
edges <- edges.mesh(8, 8)
coords <- grip.layout(edges, n = 64, dim = 2, preset = "mesh", seed = 1)


## -----------------------------------------------------------------------------
# Adjacency-list input with weights
adj_list <- list(c(2L), c(1L, 3L), c(2L, 4L), c(3L))
weight_list <- list(c(1.0), c(1.0, 2.0), c(2.0, 1.5), c(1.5))
coords <- grip.layout(adj_list = adj_list, weight_list = weight_list,
                       n = 4, dim = 2, seed = 12)


## ----mesh-plot, fig.cap="An 8x8 mesh laid out with the mesh preset in 2D.", fig.width=4.5, fig.height=4.5----
edges <- edges.mesh(8, 8)
coords <- grip.layout(edges, n = 64, dim = 2, preset = "mesh", seed = 1)
grip.plot(coords, edges,
          pch = 16, cex = 0.6,
          axes = FALSE, xlab = "", ylab = "", frame.plot = FALSE,
          main = "8x8 mesh (mesh preset)")


## ----torus-plot, fig.cap="An 8x12 torus laid out in 3D with the torus preset, shown as a static orthographic projection.", fig.width=5, fig.height=4.5----
edges <- edges.torus(8, 12)
coords <- grip.layout(edges, n = max(edges), dim = 3,
                       preset = "torus", seed = 3)
grip.plot(coords, edges, projection = "ortho", main = "Torus (8x12)")


## -----------------------------------------------------------------------------
edges <- edges.mesh(5, 5)
coords <- grip.layout(edges, n = 25, dim = 2, preset = "mesh", seed = 1)
score <- grip.score.layout(coords, edges = edges, n = 25)
paper_kable(
  score,
  caption = paper_table_caption(
    "Quality metrics for a single 5x5 mesh layout.",
    "nV = vertices; nE = edges; Dim = layout dimension; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; MedEL = median edge length; NESR = sampled non-edge separation ratio."
  ),
  digits = 3
)


## -----------------------------------------------------------------------------
edges <- edges.mesh(6, 6)
cmp <- grip.compare.layouts(
  edges = edges, n = 36, dim = 2,
  candidates = c("default", "mesh"),
  seeds = 1:3
)
paper_kable(
  cmp$summary[, c("candidate", "score.composite",
                  "sampled.stress.mean", "edge.length.cv.mean",
                  "sampled.nonedge.sep.ratio.mean",
                  "stability.procrustes.mean")],
  caption = paper_table_caption(
    "Comparison of default and mesh candidates across seeds on a 6x6 mesh.",
    "Cand = candidate; Comp = composite score; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; PStab = Procrustes stability."
  ),
  digits = 3
)


## ----carpet-compare, fig.cap="Level-3 Sierpinski carpet with default parameters (left) and the carpet preset (right). The preset recovers the fractal hole structure more clearly.", fig.width=10, fig.height=4.5----
edges <- edges.sierpinski.carpet(3)
n <- max(edges)

carpet.default <- grip.layout(edges, n = n, dim = 2, seed = 12)
carpet.preset  <- grip.layout(edges, n = n, dim = 2, preset = "carpet", seed = 12)

op <- par(mfrow = c(1, 2), mar = c(1, 1, 3, 1))
grip.plot(carpet.default, edges,
          main = "Carpet default", pch = 16, cex = 0.3,
          axes = FALSE, xlab = "", ylab = "", frame.plot = FALSE)
grip.plot(carpet.preset, edges,
          main = "Carpet preset", pch = 16, cex = 0.3,
          axes = FALSE, xlab = "", ylab = "", frame.plot = FALSE)
par(op)


## -----------------------------------------------------------------------------
carpet.cmp <- grip.compare.layouts(
  edges = edges, n = n, dim = 2,
  candidates = c("default", "carpet"),
  seeds = 1:3
)
paper_kable(
  carpet.cmp$summary[, c("candidate", "score.composite",
                          "sampled.stress.mean", "edge.length.cv.mean",
                          "sampled.nonedge.sep.ratio.mean",
                          "stability.procrustes.mean")],
  caption = paper_table_caption(
    "Comparison of default and carpet presets on the level-3 Sierpinski carpet.",
    "Cand = candidate; Comp = composite score; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; PStab = Procrustes stability."
  ),
  digits = 3
)


## -----------------------------------------------------------------------------
find.extdata.file <- function(...) {
  rel.path <- file.path(...)
  candidates <- c(
    system.file("extdata", rel.path, package = "grip"),
    file.path("..", "inst", "extdata", rel.path),
    file.path("inst", "extdata", rel.path)
  )
  path <- candidates[file.exists(candidates)][1L]
  if (!length(path) || is.na(path) || !nzchar(path))
    stop("could not locate ", rel.path)
  path
}

read.extdata.csv <- function(file.name) {
  utils::read.csv(find.extdata.file(file.name), stringsAsFactors = FALSE)
}

read.extdata.rds <- function(...) {
  readRDS(find.extdata.file(...))
}

karate.edges <- as.matrix(read.extdata.csv("karate-club-edges.csv"))
karate.n <- max(karate.edges)
labels.df <- read.extdata.csv("karate-club-membership.csv")
karate.club <- labels.df$club[order(labels.df$vertex)]


## -----------------------------------------------------------------------------
karate.presets <- grip.compare.layouts(
  edges = karate.edges, n = karate.n, dim = 3,
  candidates = c("default", "tree", "mesh"),
  seeds = 1:3,
  sample.size.stress = 1000L,
  sample.size.nonedge = 2000L,
  edge.crossings = "never",
  return.layouts = TRUE
)
paper_kable(
  karate.presets$summary[, c("candidate", "score.composite",
    "sampled.stress.mean", "edge.length.cv.mean",
    "sampled.nonedge.sep.ratio.mean",
    "stability.procrustes.mean")],
  caption = paper_table_caption(
    "Preset shortlisting on the Zachary karate club graph in 3D.",
    "Cand = candidate; Comp = composite score; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; PStab = Procrustes stability."
  ),
  digits = 3
)


## -----------------------------------------------------------------------------
karate.base <- karate.presets$summary[1, , drop = FALSE]
karate.search <- list(
  candidate.prefix = "karate.local",
  placement = karate.base$placement[[1L]],
  rounds = karate.base$rounds[[1L]],
  final_rounds = sort(unique(as.integer(c(
    max(32L, karate.base$final.rounds[[1L]] - 32L),
    karate.base$final.rounds[[1L]],
    karate.base$final.rounds[[1L]] + 32L
  )))),
  num_init = karate.base$num.init[[1L]],
  num_nbrs = sort(unique(as.integer(c(
    max(4L, karate.base$num.nbrs[[1L]] - 4L),
    karate.base$num.nbrs[[1L]],
    karate.base$num.nbrs[[1L]] + 4L
  )))),
  r = karate.base$r[[1L]],
  s = karate.base$s[[1L]],
  repulsion_factor = sort(unique(c(
    max(0, karate.base$repulsion.factor[[1L]] - 0.5),
    karate.base$repulsion.factor[[1L]],
    karate.base$repulsion.factor[[1L]] + 0.5
  )))
)
if (!is.na(karate.base$preset[[1L]]) && nzchar(karate.base$preset[[1L]]))
  karate.search$preset <- karate.base$preset[[1L]]

karate.local <- grip.compare.layouts(
  edges = karate.edges, n = karate.n, dim = 3,
  search = karate.search,
  seeds = 1:2,
  sample.size.stress = 1000L,
  sample.size.nonedge = 2000L,
  edge.crossings = "never",
  return.layouts = TRUE
)
karate.local.display <- head(karate.local$summary[, c(
  "candidate", "score.composite",
  "sampled.stress.mean", "sampled.nonedge.sep.ratio.mean",
  "stability.procrustes.mean"
)], 6)
karate.local.display$candidate <- compact_search_candidate(karate.local.display$candidate)

paper_kable(
  karate.local.display,
  caption = paper_table_caption(
    "Top local-search candidates around the leading karate preset.",
    "Cand = candidate code; fr = final rounds; nn = neighborhood count; rf = repulsion factor; Comp = composite score; Stress = sampled stress; NESR = sampled non-edge separation ratio; PStab = Procrustes stability."
  ),
  digits = 3
)


## -----------------------------------------------------------------------------
karate.local.best <- karate.local$summary[1, , drop = FALSE]
karate.metadata <- grip.compare.layouts(
  edges = karate.edges, n = karate.n, dim = 3,
  candidates = list(
    default = NULL,
    tuned = grip.params.from.summary(karate.local.best)
  ),
  clusters = karate.club,
  seeds = 1:3,
  sample.size.stress = 1000L,
  sample.size.nonedge = 2000L,
  edge.crossings = "never",
  return.layouts = TRUE
)
paper_kable(
  karate.metadata$summary[, c("candidate", "score.composite",
    "sampled.stress.mean", "cluster.separation.mean")],
  caption = paper_table_caption(
    "Metadata-aware comparison of the default and tuned karate layouts.",
    "Cand = candidate; Comp = composite score; Stress = sampled stress; ClSep = cluster separation."
  ),
  digits = 3
)


## ----karate-final, fig.cap="Zachary karate club with a tuned tree-derived 3D layout, colored by faction membership (green = Mr.\\ Hi, orange = Officer). Two orthographic views of the static layout.", fig.width=9, fig.height=4----
karate.figure.params <- list(
  preset = "tree",
  repulsion_factor = 4,
  rounds = 160L,
  final_rounds = 224L,
  num_nbrs = 16L,
  r = 0.08,
  s = 6
)

karate.figure <- grip.compare.layouts(
  edges = karate.edges, n = karate.n, dim = 3,
  candidates = list(tuned = karate.figure.params),
  clusters = karate.club,
  seeds = 1:3,
  sample.size.stress = 1000L,
  sample.size.nonedge = 2000L,
  edge.crossings = "never",
  return.layouts = TRUE
)

ok.runs <- karate.figure$runs[karate.figure$runs$status == "ok", , drop = FALSE]
best.run <- ok.runs[order(
  -ok.runs$cluster.separation,
  -ok.runs$sampled.nonedge.sep.ratio,
  ok.runs$sampled.stress,
  ok.runs$seed
), , drop = FALSE][1, , drop = FALSE]

best.coords <- karate.figure$layouts$tuned[[as.character(best.run$seed[[1L]])]]
best.coords <- prcomp(best.coords, center = TRUE, scale. = FALSE)$x
club.cols <- ifelse(karate.club == "Mr. Hi", "#1b9e77", "#d95f02")

op <- par(mfrow = c(1, 2), mar = c(1, 1, 3, 1))
grip.plot(best.coords, karate.edges, projection = "ortho",
          azimuth = 25, elevation = 20,
          vertex.col = club.cols, main = "View 1")
grip.plot(best.coords, karate.edges, projection = "ortho",
          azimuth = -55, elevation = 30,
          vertex.col = club.cols, main = "View 2")
par(op)


## -----------------------------------------------------------------------------
data(hmp.u01.gc.coarse)
cat("Vertices:", length(hmp.u01.gc.coarse$adj_list), "\n")
cat("CST levels:", paste(sort(unique(hmp.u01.gc.coarse$vertex_data$cst)),
                          collapse = ", "), "\n")


## ----eval=FALSE---------------------------------------------------------------
# # Preset shortlisting (not run in paper build)
# cmp <- grip.compare.layouts(
#   adj_list = hmp.u01.gc.coarse$adj_list,
#   weight_list = hmp.u01.gc.coarse$weight_list,
#   n = length(hmp.u01.gc.coarse$adj_list),
#   dim = 3,
#   candidates = c("default", "tree", "torus"),
#   clusters = hmp.u01.gc.coarse$vertex_data$cst,
#   seeds = 1,
#   sample.size.stress = 1200,
#   sample.size.nonedge = 3000
# )


## ----eval=FALSE---------------------------------------------------------------
# # Local search around strongest region (not run in paper build)
# search.cmp <- grip.compare.layouts(
#   adj_list = hmp.u01.gc.coarse$adj_list,
#   weight_list = hmp.u01.gc.coarse$weight_list,
#   n = length(hmp.u01.gc.coarse$adj_list),
#   dim = 3,
#   search = list(
#     candidate.prefix = "hmp.local",
#     placement = "barycenter",
#     rounds = 192L,
#     final_rounds = c(224L, 288L),
#     num_init = 30L,
#     num_nbrs = 10L,
#     r = 0.10, s = 2.0,
#     repulsion_factor = c(0.75, 1.25)
#   ),
#   clusters = hmp.u01.gc.coarse$vertex_data$cst,
#   seeds = 1,
#   sample.size.stress = 1200,
#   sample.size.nonedge = 3000
# )


## ----hmp-layouts, fig.cap="Precomputed 3D layouts of the 1,828-vertex HMP microbial network colored by community state type (CST). Left: default parameters. Center: tree preset. Right: torus preset. The tree and torus presets both produce cleaner separation of the CST-associated arms.", fig.width=11, fig.height=4----
hmp.results <- tryCatch({
  path <- system.file("extdata", "hmp_u01_gc_coarse",
                       "vignette_results.rds", package = "grip")
  if (nzchar(path)) readRDS(path) else NULL
}, error = function(e) NULL)

if (!is.null(hmp.results)) {
  edge.matrix.from.adj <- function(adj.list) {
    edges <- list(); idx <- 0L
    for (u in seq_along(adj.list)) {
      nbrs <- adj.list[[u]][adj.list[[u]] > u]
      for (v in nbrs) { idx <- idx + 1L; edges[[idx]] <- c(u, v) }
    }
    do.call(rbind, edges)
  }
  hmp.edges <- edge.matrix.from.adj(hmp.u01.gc.coarse$adj_list)
  hmp.cst <- hmp.u01.gc.coarse$vertex_data$cst
  cst.levels <- sort(unique(hmp.cst))
  cst.cols <- setNames(
    grDevices::hcl.colors(length(cst.levels), "Dark 3"),
    cst.levels
  )
  hmp.cst.col <- cst.cols[hmp.cst]

  op <- par(mfrow = c(1, 3), mar = c(1, 1, 3, 1))
  grip.plot(hmp.results$layouts$preset$default, hmp.edges,
            projection = "ortho", vertex.col = hmp.cst.col, main = "default")
  grip.plot(hmp.results$layouts$preset$tree, hmp.edges,
            projection = "ortho", vertex.col = hmp.cst.col, main = "tree")
  grip.plot(hmp.results$layouts$preset$torus, hmp.edges,
            projection = "ortho", vertex.col = hmp.cst.col, main = "torus")
  par(op)
} else {
  message("HMP precomputed results not available; skipping figure.")
}


## -----------------------------------------------------------------------------
benchmark.results <- read.extdata.rds("vs_alternatives", "benchmark_results.rds")

benchmark.methods <- c(
  "FR (igraph)",
  "KK (igraph)",
  "DrL (igraph)",
  "grip default",
  "grip tuned"
)
score.all <- benchmark.results$karate$scores[
  match(benchmark.methods, benchmark.results$karate$scores$method),
  c("method", "sampled.stress", "edge.length.cv",
    "sampled.nonedge.sep.ratio", "cluster.separation",
    "edge.crossings")
]
score.all$method <- c(
  "FR (igraph)",
  "KK (igraph)",
  "DrL (igraph)",
  "GRIP default",
  "GRIP tuned"
)

paper_kable(
  score.all,
  caption = paper_table_caption(
    "Illustrative 2D comparison on the Zachary karate club graph.",
    "Meth = method; Stress = sampled stress; EdgeCV = edge-length coefficient of variation; NESR = sampled non-edge separation ratio; ClSep = cluster separation; Cross = edge crossings."
  ),
  digits = 3
)

