# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grip_layout_cpp <- function(edges, edge_weights, n, dim, engine, placement, rounds, final_rounds, num_init, num_nbrs, r, s, tinit_factor, seed) {
    .Call(`_grip_grip_layout_cpp`, edges, edge_weights, n, dim, engine, placement, rounds, final_rounds, num_init, num_nbrs, r, s, tinit_factor, seed)
}

grip_layout_adj_cpp <- function(adj_list, weight_list, n, dim, engine, placement, rounds, final_rounds, num_init, num_nbrs, r, s, tinit_factor, seed) {
    .Call(`_grip_grip_layout_adj_cpp`, adj_list, weight_list, n, dim, engine, placement, rounds, final_rounds, num_init, num_nbrs, r, s, tinit_factor, seed)
}

